services:
  unitree_sim:
    volumes:
      - ..:/workspace/src/
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /mnt/wslg:/mnt/wslg
      - /root/.gazebo/models/:/root/.gazebo/models/
      - /var/run/docker.sock:/var/run/docker.sock
      - $HOME/.Xauthority:/tmp/.Xauthority:rw
    environment:
      - DISPLAY=${DISPLAY}
      - XAUTHORITY=/tmp/.Xauthority
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp

    working_dir: /workspace

    cap_add:
      - SYS_PTRACE

    build:
      context: .
      dockerfile: Dockerfile

    privileged: true
    network_mode: "host"

    # Keep the container alive
    command: sleep infinity
